CREATE TABLE app_user
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255),
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  role VARCHAR(255) NOT NULL,
  auth_provider VARCHAR(255) NOT NULL,
  enabled BOOLEAN NOT NULL,
  CONSTRAINT pk_appuser PRIMARY KEY (id)
);

CREATE TABLE book
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  year INTEGER,
  book_subject VARCHAR(255),
  location VARCHAR(255),
  number_of_books INTEGER,
  books_available INTEGER,
  rating DOUBLE PRECISION,
  CONSTRAINT pk_book PRIMARY KEY (id)
);

create table app_user_rented_books
(
    app_user_id BIGINT NOT NULL,
    rented_books_id BIGINT NOT NULL,
    primary key (app_user_id, rented_books_id)
);

CREATE TABLE confirmation_token
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  confirmed_at TIMESTAMP WITHOUT TIME ZONE,
  app_user_id BIGINT NOT NULL,
  CONSTRAINT pk_confirmationtoken PRIMARY KEY (id)
);

CREATE TABLE record
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  action VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  number_of_books INTEGER NOT NULL,
  date date NOT NULL,
  CONSTRAINT pk_record PRIMARY KEY (id)
);

alter table app_user_rented_books
   add constraint UK_535nfb36qnkngdibiwpl8wjci unique (rented_books_id);

alter table app_user_rented_books
   add constraint FK7r7hotkn3yu2jdn201j1d0y1d
   foreign key (rented_books_id)
   references book (id);

alter table app_user_rented_books
   add constraint FKfwqxcv6yevl48qin1r9ob8u6s
   foreign key (app_user_id)
   references app_user (id);

alter table confirmation_token
   add constraint FKo9fl25wqyh7w7mnfkdqen1rcm
   foreign key (app_user_id)
   references app_user (id);